apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: myeks
  region: ap-northeast-2

nodeGroups:
  - name: spot-ng
    instanceType: mixed
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: goorm-202408
    instancesDistribution:
      instanceTypes: ["t3.medium", "t3.large", "t3.xlarge"]
      maxPrice: 0.08
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotInstancePools: 2

