# Mount the secret "argocd-okta-ca" as volume
# - op: add
#   path: /spec/template/spec/volumes/-
#   value:
#     # This is the volume name 
#     name: okta-ca
#     secret:
#       # Please write the secret name
#       secretName: argocd-okta-ca
#       items:
#       - key: caData-v2
#         path: caData-v2.pem

# # Use the volume in the container
# - op: add
#   path: /spec/template/spec/containers/0/volumeMounts/-
#   value:
#     mountPath: /var/run/secrets/okta/

#     # Please use the volume name here 
#     name: okta-ca