apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
    {{- end }}
  selector:
    {{- include "demo.selectorLabels" . | nindent 4 }}
