---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-sample-runner
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/DevopsArtFactory/k8s-app-cahrt
      targetRevision: main
      path: actions-runner
      helm:
        valueFiles:
          - $values/tmcdapne2-nhwy/actions-runner/springboot-sample/values.yaml
    - repoURL: https://github.com/DevopsArtFactory/k8s-chart-value.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: actions-runner-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true