apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: css-secretsmanager
spec:
  # provider field contains the configuration to access the provider
  # which contains the secret exactly one provider must be configured.
  provider:
    # (1): AWS Secrets Manager
    # aws configures this store to sync secrets using AWS Secret Manager provider
    aws:
      service: SecretsManager
      region: ap-northeast-2
      # Auth defines the information necessary to authenticate against AWS
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: css-parameterstore
spec:
  # provider field contains the configuration to access the provider
  # which contains the secret exactly one provider must be configured.
  provider:
    # (1): AWS Secrets Manager
    # aws configures this store to sync secrets using AWS Secret Manager provider
    aws:
      service: ParameterStore
      region: ap-northeast-2
      # Auth defines the information necessary to authenticate against AWS
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
